title: "Welcome to Database Management Systems (MGT 4058)!"
theme: jekyll-theme-minimal

description: >
  By Zhaohu (Jonathan) Fan <br />
  "A well-structured database is the backbone of informed decisions."

show_downloads: false
github:
  is_project_page: false
